import 'package:education_app/resources/color.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class FaqsScreen extends StatelessWidget {
  final List<Map<String, String>> faqs = [
    {
      'q': 'What subscription plans do you offer?',
      'a': 'We offer 3-month, 6-month, and 1-year subscription plans.'
    },
    {
      'q': 'What payment methods can I use?',
      'a':
          'You can pay via bank account transfer, JazzCash, or EasyPaisa. After payment, please share the receipt with us. Online payment gateway method is being integrated and it will be available soon.'
    },
    {
      'q': 'What is a promo code?',
      'a':
          'A promo code is a unique code that provides a discount on your subscription.'
    },
    {
      'q': 'Can I reuse my promo code?',
      'a':
          'No, once a promo code is used, it becomes expired and cannot be reused.'
    },
    {
      'q': 'Where can I get promo codes?',
      'a':
          'Many institutions and teachers have promo codes that they offer to students free of cost. If you\'re a group of five or more, you can also contact our admin to request a promo code.'
    },
    {
      'q': 'I’m a teacher. How can I get promo codes for my students?',
      'a':
          'Please contact our admin to request institutional promo codes. Our representative will get in touch with you.'
    },
    {
      'q': 'Can I renew or upgrade my subscription before it expires?',
      'a': 'Yes, you can upgrade or renew your subscription at any time.'
    },
    {
      'q': 'I can’t reset my filters. What should I do?',
      'a':
          'You can reset your filters once. If you need additional resets, please contact the admin. Requests are handled on a case-by-case basis.'
    },
    {
      'q': 'Can I contribute to the question pool?',
      'a':
          'Yes, you can contribute by giving feedback or joining our team. Contact our admin to get started.'
    },
    {
      'q': 'Are the questions generated by AI?',
      'a':
          'No, all questions are created by human experts and experienced teachers.'
    },
    {
      'q': 'What is the role of AI on this platform?',
      'a':
          'AI helps in shuffling questions and selecting them from different difficulty-level pools based on the test requirements. The difficulty level of each question is set by expert teachers, and all questions are tagged accordingly in the backend.'
    },
    {
      'q': 'Does my performance remain saved?',
      'a':
          'Yes, your performance data remains saved unless you reset filters and manually delete previous results.'
    },
    {
      'q':
          'What activities can lead to denial of access to my account, and how is it monitored?',
      'a':
          'Attempting to copy our question pool through screenshots, copy-pasting, screen recording, or any other method will result in denial of access to your account. Our system notifies the admin team of such activities, and your access may be blocked for violating our terms and conditions. Additionally, we monitor other platforms, and if we find our content being shared without permission, we reserve the right to pursue legal action. All our data is protected under copyright law. We follow ZERO-TOLERANCE policy for copyright.'
    },
    {
      'q': 'Can I access the platform on multiple devices?',
      'a':
          'Yes, you can log in from different devices, but simultaneous logins from multiple devices may lead to automatic logout or access restrictions for security reasons.'
    },
    {
      'q': 'Do you offer any free trial or demo?',
      'a':
          'We do not offer a free trial, but FIVE demo questions in each chapter are available for all subjects.'
    },
    {
      'q': 'How often are new questions added?',
      'a':
          'New questions are added regularly by our expert teachers to ensure the content stays fresh, relevant, and aligned with updated syllabi.'
    },
    {
      'q': 'What should I do if I find a mistake in a question or explanation?',
      'a':
          'Please use the feedback option available with each question or contact our admin directly. We value your input and will verify and correct it promptly if needed.'
    },
    {
      'q': 'Is my personal information secure?',
      'a':
          'Yes, we take data privacy seriously. Your personal and payment information is stored securely and never shared with third parties.'
    },
    {
      'q': 'Can I pause my subscription if I need a break?',
      'a':
          'Currently, we do not offer a pause or hold option. However, you can contact admin for special consideration depending on the reason and duration.'
    },
    {
      'q': 'What if I forgot my password or can’t log in?',
      'a':
          'Use the "Forgot Password" option on the login page to reset your password. If the problem persists, please contact our support team or admin.'
    },
    {
      'q': 'Will I get a certificate after completing tests?',
      'a':
          'We do not offer certificates. However, your performance reports and analytics are available to help you track your progress and improvement.'
    },
    {
      'q': 'Are there explanations provided for the answers?',
      'a': 'Yes, every question comes with detailed explanation.'
    },
    {
      'q': 'Can I take the same test multiple times?',
      'a':
          'Yes, you can retake tests. However, the questions may be shuffled or changed slightly to provide a more effective learning experience.'
    },
    {
      'q': 'Is the platform available in languages other than English?',
      'a':
          'Currently, the platform is primarily in English. However, we are working on adding support for other languages in future updates.'
    },
    {
      'q': 'Can I create my own custom test?',
      'a':
          'Yes, our platform allows you to create custom tests by selecting specific subject, timed/ tutor mode, filters to include selected questions and number of questions.'
    },
    {
      'q':
          'After uploading fee payment receipt, how much is waiting period to get access to question pool.',
      'a':
          'Its usually one working day, however if you need it urgent, please what’s app us with request for urgent approval.'
    },
    {
      'q': 'How can I contact support or the admin team?',
      'a':
          'You can contact our support or admin team via WhatsApp, email, or the in-app feedback form. Response time is usually within 24 hours. If some matter is for urgent consideration, write urgent in subject for rapid response.'
    },
    {
      'q': 'Is the app available on both Android and iOS?',
      'a':
          'The app is available on Android. iOS support is in development and will be launched soon.'
    },
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: Text(
          'FAQs',
          style: GoogleFonts.poppins(
            fontSize: 24,
            fontWeight: FontWeight.bold,
            color: Colors.white,
          ),
        ),
        centerTitle: true,
        backgroundColor: AppColors.indigo,
        elevation: 0.5,
        foregroundColor: Colors.black,
        leading: IconButton(onPressed: (){
          Navigator.pop(context);
        }, icon: Icon(Icons.arrow_back_ios, color: Colors.white)),
      ),
      body: ListView.builder(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
        itemCount: faqs.length,
        itemBuilder: (context, index) {
          final item = faqs[index];
          return Padding(
            padding: const EdgeInsets.symmetric(vertical: 10),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Q${index + 1}: ${item['q']}',
                  style: GoogleFonts.poppins(
                    fontSize: 16,
                    fontWeight: FontWeight.w600,
                    color: Colors.black87,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  'A: ${item['a']}',
                  style: GoogleFonts.poppins(
                    fontSize: 15,
                    color: Colors.black54,
                  ),
                ),
                const SizedBox(height: 6),
                Divider(color: Colors.grey.shade300),
              ],
            ),
          );
        },
      ),
    );
  }
}
